### ISSUE TITLE
A quick question about /store/thunk.js

### ISSUE THREAD

**Issue by armenr** [granmoe/react-redux-async-await-boilerplate#2]
I'm having trouble unspooling the code in the following file:

/store/thunk.js
```
export default ({ dispatch, getState }) =>
  next => action =>
    typeof action === 'function'
      ? action(dispatch, getState)
      : next(action)

```

Could you please explain what purpose this file serves, and why you've gone about implementing your thunks this way, rather than the vanilla implementation of redux thunks?

I'd be very grateful for your explanation - as I couldn't find much about that in your README. 

Thanks again!

**Comment by granmoe** [comment]
> Could you please explain what purpose this file serves, and why you've gone about implementing your thunks this way, rather than the vanilla implementation of redux thunks?

My only reason for using my own is because it was easy to do, works exactly the same way, and is less code and perhaps more simple and minimal than installing the official package :-)

It almost seems like overkill to have a package that provides you such a simple, minimal, single function, but I do understand that the official package has a lot more safety checks and resiliency than my version, which some people might want.

If you want to understand how thunk works, I would say look at the official redux docs :-)

**Comment by armenr** [comment]
Thanks for the prompt and courteous response. That helps to clarify!
